networks:
    web:
        external: false

volumes:
    redis-data: {}
    postgres-data: {}

services:
    postgres:
        image: postgres:16-alpine
        container_name: bankthing-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - web

    redis:
        image: redis:7-alpine
        container_name: bankthing-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - web

    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile.prod
        image: bankthing-nest-backend:prod
        container_name: bankthing-backend
        restart: unless-stopped
        expose:
            - "9095"
        ports:
            - "9095:9095"
        env_file:
            - ../backend/.env
        environment:
            REDIS_HOST: redis
            REDIS_PORT: "6379"
            POSTGRES_HOST: postgres
            POSTGRES_PORT: "5432"
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        depends_on:
            - postgres
            - redis
        networks:
            - web

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile.prod
            args:
                VITE_API_BASE_URL: localhost:9095
        image: bankthing-react-frontend:prod
        container_name: bankthing-frontend
        restart: unless-stopped
        expose:
            - "80"
        ports:
            - "80:80"
        networks:
            - web
